#AutoApiS 多功能版
name: Auto Api Super

on:
  schedule:
    - cron: "0 1,5,9 * * 1-6"
  watch:
    types: [ started ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set up Python #安装python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install requests #安装requests
        run: |
          pip install requests pycryptodome
      - name: Test Api #Api调用
        env:
          ID_LIST: ${{ secrets.ID_LIST }} # secrets_id 提供
          KEY_LIST: ${{ secrets.KEY_LIST }} # secrets_key 提供
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python TestApi.py $PASSWORD $ID_LIST $KEY_LIST
